### ISSUE TITLE
User-level setting max_partitions_per_insert_block is specified in the wrong place

### ISSUE THREAD

**Issue by jzombi** [AlexeySetevoi/ansible-clickhouse#45]
The `max_partitions_per_insert_block` is currently specified in config.xml ([ansible-clickhouse/templates/config.j2](https://github.com/AlexeySetevoi/ansible-clickhouse/blob/f822cef39d1bfc73f0e82921d9f5da08886b5f48/templates/config.j2#L78)), but it
should be specified under the `<profiles>` element in `users.xml` config file (see [1](https://clickhouse.tech/docs/en/operations/settings/), [2](https://clickhouse.tech/docs/en/operations/settings/query-complexity/#max-partitions-per-insert-block)):

```
<yandex>
    <profiles>
        <default>
            <max_partitions_per_insert_block>100</max_partitions_per_insert_block>
...
```

Since version 20.5.2.7 this misconfiguration prevents the clickhouse-server from starting (ClickHouse/ClickHouse#11449).

**Comment by AlexeySetevoi** [comment]
fixed

**Comment by jzombi** [comment]
Thanks!
