### ISSUE TITLE
Adding 0.0.0.0 to clickhouse_listen_host_custom results in "Address already in use" error

### ISSUE THREAD

**Issue by AntonFriberg** [AlexeySetevoi/ansible-clickhouse#68]
Hi! Thanks for writing this role and great job!

I noticed that simply adding `0.0.0.0` to `clickhouse_listen_host_custom` does not work with ClickHouse version `21.12.3.32` due to errors that the address is already in use.

```
2022.01.10 13:48:18.227905 [ 13691 ] {} <Error> Application: DB::Exception: Listen [0.0.0.0]:8123 failed: Poco::Exception. Code: 1000, e.code() = 98, Net Exception: Address already in use: 0.0.0.0:8123 (version 21.12.3.32 (official build))
```

This seems to be due to the construction of `clickhouse_listen_host` where `clickhouse_listen_host_default` is added together with `clickhouse_listen_host_custom`. https://github.com/AlexeySetevoi/ansible-clickhouse/blob/master/defaults/main.yml#L34

```
clickhouse_listen_host_default:
  - "::1"
  - "127.0.0.1"

clickhouse_listen_host_custom: []

clickhouse_listen_host: "{{ clickhouse_listen_host_default + clickhouse_listen_host_custom }}"
```

It seems ClickHouse does not allow overlapping IP addresses in the listen configuration.  I solved it by simply setting the `clickhouse_listen_host` directly. So if you want to listen on all interfaces and both ipv6 and ipv4 it would look like this.

```
clickhouse_listen_host: 
  - "::"
```

Since this is the case I think it would be valuable for the reader to know in the `README.md`.  Do you want me to add how to listen on all interfaces as an example in the `README.md` as a PR?

**Comment by AlexeySetevoi** [comment]
Hi! Thanks for your time!
Yes, if you can make PR - make it.

**Comment by AntonFriberg** [comment]
Updated this issue since I noticed that you can not have both `0.0.0.0` and `::` either so if you want both ipv4 and ipv6 then you should only have `::`. Tested locally using vagrant.

**Comment by AntonFriberg** [comment]
Also changed so that I use `::/0` since that was needed for users.xml and `::` did not work in that case.
